services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - host-monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml 
    networks:
      - host-monitoring
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro 
      - /sys:/host/sys:ro 
      - /:/rootfs:ro
    networks:
      - host-monitoring
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager:/config"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug

  mongodb:
    image: "mongo:7.0"
    container_name: mongodb
    restart: "on-failure"
    volumes:
      - "mongodb_data:/data/db"
      - "mongodb_config:/data/configdb"
    networks:
      - host-monitoring 

  datanode:
    image: "${DATANODE_IMAGE:-graylog/graylog-datanode:7.0}"
    container_name: datanode
    restart: "on-failure"
    hostname: "datanode"
    ports:
      - "127.0.0.1:8999:8999/tcp"   # DataNode API
      - "127.0.0.1:9200:9200/tcp"
      - "127.0.0.1:9300:9300/tcp"
    volumes:
      - "graylog-datanode:/var/lib/graylog-datanode"
    networks:
      - host-monitoring 
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536

  graylog:
    image: "${GRAYLOG_IMAGE:-graylog/graylog-enterprise:7.0}"
    container_name: graylog
    hostname: "server"
    restart: "on-failure"
    ports:
      - "127.0.0.1:5044:5044/tcp"   # Beats
      - "127.0.0.1:5140:5140/tcp"   # Syslog TCP
      - "127.0.0.1:5140:5140/udp"   # Syslog UDP
      - "127.0.0.1:5555:5555/tcp"   # RAW TCP
      - "127.0.0.1:5555:5555/udp"   # RAW UDP
      - "127.0.0.1:9000:9000/tcp"   # Server API
      - "127.0.0.1:12201:12201/tcp" # GELF TCP
      - "127.0.0.1:12201:12201/udp" # GELF UDP
      - "127.0.0.1:13301:13301/tcp" # Forwarder data
      - "127.0.0.1:13302:13302/tcp" # Forwarder config
    volumes:
      - "graylog_data:/usr/share/graylog/data"
    networks:
      - host-monitoring 
    depends_on:
      mongodb:
        condition: "service_started"
      datanode:
        condition: "service_started"
    entrypoint: "/usr/bin/tini --  /docker-entrypoint.sh"

networks:
  host-monitoring:
    driver: bridge

volumes:
  grafana_data:
  prometheus_data:
  mongodb_data:
  mongodb_config:
  graylog-datanode:
  graylog_data:
  alertmanager-data: